/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsProvidersRouteImport } from './routes/docs/providers'
import { Route as DocsPlaygroundRouteImport } from './routes/docs/playground'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsExamplesRouteImport } from './routes/docs/examples'
import { Route as DocsCoreConceptsRouteImport } from './routes/docs/core-concepts'
import { Route as DocsCommunityRouteImport } from './routes/docs/community'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProvidersRoute = DocsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundRoute = DocsPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCoreConceptsRoute = DocsCoreConceptsRouteImport.update({
  id: '/core-concepts',
  path: '/core-concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommunityRoute = DocsCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/community': typeof DocsCommunityRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/community': typeof DocsCommunityRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/community': typeof DocsCommunityRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/providers': typeof DocsProvidersRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/api/$'
    | '/docs/api-reference'
    | '/docs/community'
    | '/docs/core-concepts'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/playground'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/docs/api-reference'
    | '/docs/community'
    | '/docs/core-concepts'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/playground'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/api/$'
    | '/docs/api-reference'
    | '/docs/community'
    | '/docs/core-concepts'
    | '/docs/examples'
    | '/docs/installation'
    | '/docs/playground'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/providers': {
      id: '/docs/providers'
      path: '/providers'
      fullPath: '/docs/providers'
      preLoaderRoute: typeof DocsProvidersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground': {
      id: '/docs/playground'
      path: '/playground'
      fullPath: '/docs/playground'
      preLoaderRoute: typeof DocsPlaygroundRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/core-concepts': {
      id: '/docs/core-concepts'
      path: '/core-concepts'
      fullPath: '/docs/core-concepts'
      preLoaderRoute: typeof DocsCoreConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/community': {
      id: '/docs/community'
      path: '/community'
      fullPath: '/docs/community'
      preLoaderRoute: typeof DocsCommunityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsCommunityRoute: typeof DocsCommunityRoute
  DocsCoreConceptsRoute: typeof DocsCoreConceptsRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPlaygroundRoute: typeof DocsPlaygroundRoute
  DocsProvidersRoute: typeof DocsProvidersRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsCommunityRoute: DocsCommunityRoute,
  DocsCoreConceptsRoute: DocsCoreConceptsRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPlaygroundRoute: DocsPlaygroundRoute,
  DocsProvidersRoute: DocsProvidersRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
